### ISSUE TITLE
GitHub Hovercard Locks Firefox

### ISSUE THREAD

**Issue by progkix** [Justineo/github-hovercard#107] opened 2017-10-14 12:51 UTC
I've been experiencing this issue with the last couple of releases.

With Hovercard enabled and on a repository release page, Firefox will go Not Responding (Win) / freeze (Mac / Linux) when downloading files. I have to end / kill the Firefox process and restart it.

When Hovercard is disabled, I can download all the files without any freeze.

**Comment by Justineo** [comment] 2017-10-14 12:56
Thanks for reporting. Could you provide a reproduction URL?

**Comment by progkix** [comment] 2017-10-14 15:33
Happened this morning on these 2:

https://github.com/atom/atom/releases
https://github.com/trazyn/weweChat/releases

Also, the settings are as follows:

Delay: 200ms
Show user hovercards for myself: Checked
Show readme content for repos: Not Checked
Disable hovercard for projects: Checked

**Comment by Justineo** [comment] 2017-10-15 02:07
Thanks! I'll look into this.

**Comment by TrueFurby** [comment] 2017-10-26 08:13
This happens to me as well. Seems like it occurs when there is larger amount of data.

It does not happen for me when using links @progkix posted, but happens here for example: https://github.com/ligato/vpp-agent/commit/89a848efe3b5c4a4f75ceb134f8bd856f89162da#diff-77cf164667f1e1787f3cfd67f3a4cb13

**Comment by gluons** [comment] 2017-11-03 03:30
Me too.

**Translation:** "Scripts in **GitHub Hovercard** makes Nightly slower"

<img width="957" alt="default" src="https://user-images.githubusercontent.com/4688092/32359601-c54d022e-c081-11e7-8903-1c49bfd5d822.PNG">

**Comment by progkix** [comment] 2017-11-03 11:02
I can confirm what TrueFurby reported - large amounts of information on the release page slow down / lock up Firefox. If there's not very much on a release pages, it's not a problem.

**Comment by Justineo** [comment] 2017-11-08 06:55
Since I can't reproduce the problem on my side, I'll release a new version later with some potential performance gains on release page. Tell me if the new version will solve the problem. Thank you guys!

**Comment by progkix** [comment] 2017-11-09 15:36
I've been using 1.4.2 since it was released and have not noticed any slowdown or lockups.

And I hit some pretty heavy repos too.

**Comment by Justineo** [comment] 2017-11-09 16:02
@progkix Good to hear this. So I'm closing this now and please feel free to reopen or file new issues if that happen again.

**Closed by Justineo** 2017-11-09 16:02 UTC
