### ISSUE TITLE
API limit exceeded

### ISSUE THREAD

**Issue by TheInitializer** [Justineo/github-hovercard#20] opened 2016-03-19 20:03 UTC

**Comment by Justineo** [comment] 2016-03-20 04:31
Did the card suggest you to create and bind an access token to avoid this?

**Comment by TheInitializer** [comment] 2016-03-20 13:52
Yes, I created it and now don't know what to do with it

**Comment by Justineo** [comment] 2016-03-20 19:42
There should be a popup form to fill in the token you just created on the GitHub page you were visiting. Did you see it?

**Comment by TheInitializer** [comment] 2016-03-20 20:22
No

**Comment by TheInitializer** [comment] 2016-03-20 20:22
It just showed the little message

**Comment by Justineo** [comment] 2016-03-21 03:49
Okay I see it should be fixed in `v0.4.1`. Tell me if it works please :)

**Comment by Justineo** [comment] 2016-03-21 04:24
Sorry I'm now able to reproduce the problem right now. Does this happen all the time? And which version(Chrome/Firefox/Opera/..., version number) are you using? Does it happen on all cards (user/repo/issue)? Thanks :)

**Comment by TheInitializer** [comment] 2016-03-21 20:50
Firefox Developer Edition 47.0a2. It hasn't happened in a while, mostly because I try to not use it excessively, and when it does happen, it happens on every card.

**Comment by Justineo** [comment] 2016-03-22 06:20
@TheInitializer Thanks for the info. I'll look into this.

**Comment by Justineo** [comment] 2016-04-05 09:44
@TheInitializer Hi, I made some updates on API requests. Because I wasn't able to reproduce your problem so I'm just hoping that it's fixed in the latest version.

**Comment by marktopper** [comment] 2016-04-06 12:40
The popup does not show the actual form for inputting the API token generated.
![screen shot 2016-04-06 at 14 39 11](https://cloud.githubusercontent.com/assets/2232539/14316820/6e61692e-fc05-11e5-9bee-59737a620662.png)

**Comment by Justineo** [comment] 2016-04-06 14:00
@marktopper Did it show after you clicked the "Create a new access token" link?

**Comment by marktopper** [comment] 2016-04-07 07:16
@Justineo, will check it out.

**Comment by marktopper** [comment] 2016-04-07 07:25
I can confirm that you are right @Justineo.

![screen shot 2016-04-07 at 09 24 25](https://cloud.githubusercontent.com/assets/2232539/14343640/9e2884ec-fca2-11e5-8a9c-d519fcc1e1d9.png)

**Comment by Justineo** [comment] 2016-04-14 08:10
Closing this now. Feel free to reopen if it still occurs.

**Closed by Justineo** 2016-04-14 08:10 UTC
