### ISSUE TITLE
UI bug is glitching

### ISSUE THREAD

**Issue by codynguyen1116** [Justineo/github-hovercard#26] opened 2016-05-27 01:04 UTC
Not sure how to describe it, so I'll give a screenshot: I'm using Chrome 50.0.2661.102 on Windows 10.

![image](https://cloud.githubusercontent.com/assets/4723983/15594637/0491cdbe-237d-11e6-839d-ce66b38b1aad.png)

**Comment by Justineo** [comment] 2016-05-27 03:27
Thanks for reporting! I'm able to reproduce this problem and will look into this.

**Comment by Justineo** [comment] 2016-05-27 03:30
Oops, it seems that GitHub has updated it's styles which contain some naming conflicts with my extension.

**Comment by Justineo** [comment] 2016-05-27 03:51
@codynguyen1116 The problem is now fixed in the latest version :)

**Closed** 2016-05-27 07:41 UTC

**Comment by codynguyen1116** [comment] 2016-05-28 02:33
@Justineo thanks :D
